# Generated by Django 4.1.7 on 2023-03-29 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "age",
                    models.PositiveBigIntegerField(default=0, verbose_name="Years old"),
                ),
                (
                    "biography",
                    models.TextField(max_length=500, verbose_name="Biography"),
                ),
                ("image", models.ImageField(upload_to="actors/", verbose_name="Photo")),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Category")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                ("url", models.SlugField(max_length=150)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "age",
                    models.PositiveBigIntegerField(default=0, verbose_name="Years old"),
                ),
                (
                    "biography",
                    models.TextField(max_length=500, verbose_name="Biography"),
                ),
                ("image", models.ImageField(upload_to="actors/", verbose_name="Photo")),
            ],
            options={
                "verbose_name": "Director",
                "verbose_name_plural": "Directors",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                ("url", models.SlugField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "tagline",
                    models.CharField(
                        default="", max_length=100, verbose_name="Tagline"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                (
                    "poster",
                    models.ImageField(upload_to="movies/", verbose_name="Poster"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Release date")),
                ("country", models.CharField(max_length=40, verbose_name="Country")),
                (
                    "world_premiere",
                    models.DateField(
                        default=datetime.datetime.today, verbose_name="World premiere"
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(
                        default=0, help_text="onli dollars", verbose_name="Budget"
                    ),
                ),
                (
                    "fees_in_usa",
                    models.PositiveIntegerField(
                        default=0, help_text="only dollars", verbose_name="Fees in USA"
                    ),
                ),
                (
                    "fees_in_world",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Only dollars",
                        verbose_name="Fees in World",
                    ),
                ),
                ("url", models.SlugField(max_length=150, unique=True)),
                ("draft", models.BooleanField(default=False, verbose_name="Draft")),
                (
                    "actors",
                    models.ManyToManyField(related_name="Actors", to="movies.actor"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="Dorector", to="movies.director"
                    ),
                ),
                (
                    "ganres",
                    models.ManyToManyField(related_name="Ganre", to="movies.genre"),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
        migrations.CreateModel(
            name="RatingStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Value"),
                ),
            ],
            options={
                "verbose_name": "Rating star",
                "verbose_name_plural": "Rating stars",
            },
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("text", models.CharField(max_length=5000, verbose_name="Message")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        verbose_name="Movie",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.reviews",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_ip", models.CharField(max_length=15, verbose_name="IP adress")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.fields.CharField,
                        to="movies.movie",
                        verbose_name="Movie",
                    ),
                ),
                (
                    "star",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.ratingstar",
                        verbose_name="star",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
            },
        ),
        migrations.CreateModel(
            name="MovieShots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "Image",
                    models.ImageField(upload_to="movie_shots/", verbose_name="Image"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        verbose_name="Movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie shot",
                "verbose_name_plural": "Movie shots",
            },
        ),
        migrations.AddField(
            model_name="director",
            name="filmography",
            field=models.ManyToManyField(related_name="Filmography", to="movies.movie"),
        ),
    ]
