# Generated by Django 4.1.7 on 2023-03-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(related_name="Director", to="movies.director"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
                verbose_name="Movie",
            ),
        ),
    ]
