# Generated by Django 4.1.7 on 2023-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_directors_alter_rating_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                related_name="film_actor", to="movies.actor", verbose_name="Actors"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                related_name="film_director",
                to="movies.director",
                verbose_name="Director",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="ganres",
            field=models.ManyToManyField(to="movies.genre", verbose_name="Ganre"),
        ),
    ]
