# Generated by Django 4.1.7 on 2023-03-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_director_filmography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                null=True,
                related_name="film_director",
                to="movies.director",
                verbose_name="Director",
            ),
        ),
    ]
