# Generated by Django 4.1.7 on 2023-03-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_movie_directors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                default="",
                null=True,
                related_name="film_director",
                to="movies.director",
                verbose_name="Director",
            ),
        ),
    ]
