# Generated by Django 4.1.7 on 2023-03-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_movie_directors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="filmography",
            field=models.ManyToManyField(
                blank=True, null=True, to="movies.movie", verbose_name="Filmography"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True,
                default="",
                null=True,
                related_name="film_director",
                to="movies.director",
                verbose_name="Director",
            ),
        ),
    ]
